services:
  node-app:
    container_name: express-node-app-container
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "toor"
  redis:
    image: redis
  web:
    image: nginx:stable-alpine
    ports:
    - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
  
volumes:
  postgres-db:
